# version: '3.8'
services:
  app:
    build: .
    container_name: python-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=soho_db
      - DB_USER=user
      - DB_PASS=password
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    networks:
      - mynetwork
  
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_DB=soho_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata: